[package]
name = "dircheck"
version = "0.1.1"
edition = "2021"

[dependencies]
blake3 = { version = "1", features = ["rayon"] }
hex = "0.4"
memmap2 = "0.5.10"
rayon = "1.7"
structopt = "0.3"
thiserror = "1.0"
walkdir = "2.3"